name: service_tak_mobile
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cached_network_image: ^3.3.1
  calendar_date_picker2: ^0.5.3
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  permission_handler: ^11.2.0
  provider: ^6.1.1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_datepicker: ^24.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
